In [2]:
class Employee:
    numberOfEmployees = 0

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.numberOfEmployees+=1


def averagesalary(employee):
    total = sum(e.salary for e in employee)
    average = total / len(employee)
    return average

class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department):
        Employee.__init__(self,name, family, salary, department)

print("Employee 1: ")
employee1 = Employee(input("Enter name: "),input("Family Members: "),int(input("Employee Salary: ")),input("Employee Department: "))
print("Employee 2: ")
employee2 = Employee(input("Enter name: "),input("Family Members: "),int(input("Employee Salary: ")),input("Employee Department: "))
print("Full Time Employee 1: ")
employee3 = FulltimeEmployee(input("Enter name: "),input("Family Members: "),int(input("Employee Salary: ")),input("Employee Department: "))
print("")
print("Number of employees: ",Employee.numberOfEmployees)
listofEmployees = [employee1, employee2]
avgsalary = averagesalary(listofEmployees)
print("Avg salary is :", avgsalary)

Employee 1: 
Enter name: dheeraj
Family Members: 4
Employee Salary: 5699
Employee Department: cs
Employee 2: 
Enter name: annam
Family Members: 5
Employee Salary: 6999
Employee Department: it
Full Time Employee 1: 
Enter name: sai
Family Members: 5
Employee Salary: 7999
Employee Department: cis

Number of employees:  3
Avg salary is : 6349.0


In [3]:
import numpy

random_vector = numpy.random.uniform(1, 20, 20)
print(random_vector)
print("")
print("")
reshaped_array = random_vector.reshape(4, 5)
print("")
print("")
print(reshaped_array)
reshaped_array[numpy.arange(4), numpy.argmax(reshaped_array, axis=1)] = 0
print("")
print("")
print(reshaped_array)

[ 3.78937755  9.08469998  4.46384001 18.45640856 19.55369784  5.01445077
  2.09845478 16.36590218  8.10597527  1.60929073  3.24777342  4.13946681
 14.8987842   8.43426549 18.07094882 10.79138755  7.99557646  4.3467301
  6.9515914   4.9740878 ]




[[ 3.78937755  9.08469998  4.46384001 18.45640856 19.55369784]
 [ 5.01445077  2.09845478 16.36590218  8.10597527  1.60929073]
 [ 3.24777342  4.13946681 14.8987842   8.43426549 18.07094882]
 [10.79138755  7.99557646  4.3467301   6.9515914   4.9740878 ]]


[[ 3.78937755  9.08469998  4.46384001 18.45640856  0.        ]
 [ 5.01445077  2.09845478  0.          8.10597527  1.60929073]
 [ 3.24777342  4.13946681 14.8987842   8.43426549  0.        ]
 [ 0.          7.99557646  4.3467301   6.9515914   4.9740878 ]]
